# Generated by Django 3.0.6 on 2020-06-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCDatails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreditNum', models.CharField(max_length=20)),
                ('ExipryDate', models.CharField(max_length=5)),
                ('CVV', models.IntegerField()),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
    ]
